version: 2.1

orbs:
  orb-tools: circleci/orb-tools@volatile

master_filter: &master_filter
  filters:
    branches:
      only:
        - master

workflows:
  publish_latest:
    jobs:
      - orb-tools/pack:
          name: validate_orb
          <<: *master_filter
          source-dir: ./src/
          destination-orb-path: ./packed/orb.yml
          workspace-path: ./packed/orb.yml
          artifact-path: ./packed/orb.yml
      - orb-tools/publish:
          name: publish_orb
          <<: *master_filter
          context: orb-tools
          orb-ref: "gofunky/orbtools@dev:${CIRCLE_BRANCH}"
          publish-token-variable: "$ORB_PUBLISHING_TOKEN"
          orb-path: packed/orb.yml
          attach-workspace: true
          checkout: false
          requires:
            - validate_orb
      - orb-tools/increment:
          name: increment_orb
          <<: *master_filter
          context: orb-tools
          segment: patch
          orb-ref: gofunky/orbtools
          publish-token-variable: "$ORB_PUBLISHING_TOKEN"
          orb-path: packed/orb.yml
          attach-workspace: true
          checkout: false
          requires:
            - publish_orb
