version: 2.1

orbs:
  orbtools: gofunky/orbtools@dev:270
  envorb: gofunky/envorb@0.3.9
  docker: gofunky/docker@0.1.2

master_filter: &master_filter
  filters:
    branches:
      only:
        - master

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

pr_filter: &pr_filter
  filters:
    branches:
      ignore:
        - master

use_alpine_version: &use_alpine_version
  alpine_version: "3.8"

set_alpine_version: &set_alpine_version
  <<: *use_alpine_version
  attach: true
  variable: ALPINE_VERSION
  value: "3.8"

set_cli_version: &set_cli_version
  <<: *use_alpine_version
  variable: CLI_VERSION
  repository: "CircleCI-Public/circleci-cli"

orbtools_job: &orbtools_job
  attach: true
  base_tag: orbtools
  add_labels: true
  docker_version: 18.09.0
  context: docker-hub
  args: "VERSION=${CLI_VERSION},ALPINE=${ALPINE_VERSION},CLI=${CLI_VERSION}"

workflows:
  build_latest_image:
    jobs:
      - envorb/github:
          name: set_cli_version
          <<: *set_cli_version

      - envorb/value:
          name: set_alpine_version
          <<: *set_alpine_version

      - docker/build_test_push:
          name: build_latest
          <<: [*master_filter, *orbtools_job]
          tags: "gofunky/orbtools:${CLI_VERSION},gofunky/orbtools:${CLI_VERSION}-alpine${ALPINE_VERSION},gofunky/orbtools:alpine${ALPINE_VERSION},gofunky/orbtools:latest"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          cache: true
          requires: [set_cli_version, set_alpine_version]

      - docker/build_test:
          name: test_latest
          <<: [*pr_filter, *orbtools_job]
          tags: "gofunky/orbtools:latest"
          requires: [set_cli_version, set_alpine_version]

  build_daily_image:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          <<: *master_filter

    jobs:
      - envorb/github:
          name: set_cli_version
          <<: *set_cli_version

      - envorb/value:
          name: set_alpine_version
          <<: *set_alpine_version

      - docker/build_test_push:
          name: build_latest
          <<: [*master_filter, *orbtools_job]
          tags: "gofunky/orbtools:${CLI_VERSION},gofunky/orbtools:${CLI_VERSION}-alpine${ALPINE_VERSION},gofunky/orbtools:alpine${ALPINE_VERSION},gofunky/orbtools:latest,gofunky/orbtools:stable-alpine${ALPINE_VERSION},gofunky/orbtools:stable,gofunky/orbtools:daily"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          cache: true
          requires: [set_cli_version, set_alpine_version]

  check_orb:
    jobs:
      - orbtools/check:
          name: check_pull_request
          <<: [*pr_filter, *use_alpine_version]

  publish_orb:
    jobs:
      - orbtools/env-pack-publish:
          name: publish_latest
          context: orb-tools
          version: "dev:${CIRCLE_BUILD_NUM}"
          <<: [*master_filter, *use_alpine_version]

  release_orb:
    jobs:
      - envorb/git_tag:
          name: release_tag
          alpine_version: "3.8"
          variable: ORB_PUBLISHING_VERSION
          <<: [*tag_filter, *use_alpine_version]

      - orbtools/env-pack-publish:
          name: publish_release
          context: orb-tools
          <<: [*tag_filter, *use_alpine_version]
          requires: [release_tag]
