version: 2.1

orbs:
  orb-tools: circleci/orb-tools@dev:refactor-to-unify-publishing

workflows:
  default-workflow:
    jobs:
      - orb-tools/pack:
          source-orb-path: ./src/@orb.yml
          destination-orb-path: ./packed/orb.yml

      - orb-tools/validate:
          orb-path: ./packed/orb.yml
          requires: [orb-tools/pack]

      - orb-tools/publish:
          orb-path: ./packed/orb.yml
          orb-ref: "circleci/orb-tools@dev:${CIRCLE_BRANCH}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          requires: [orb-tools/validate]

      - orb-tools/increment:
          orb-path: orb-packed/orb.yml
          orb-ref: "circleci/orb-tools"
          segment: "patch"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          requires: [orb-tools/validate]
          filters:
            branches:
              only: master
